config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    # before_action :authenticate_user!

    def index
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :username, :age, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :username, :age, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pensieve</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<%= render 'shared/nav' %>
<br>
<h2>This is where we will put some profile information</h2>

app/views/shared/_nav.html.erb
<ul>
  <li><a <%= link_to "Your profile", profiles_path %></a></li>
  <li><a <%= link_to "Sign out", destroy_user_session_path, method: :delete %></a></li>
</ul>
 

app/views/welcome/index.html.erb
<h1>Welcome to Pensieve</h1>
<p>Let's think about saving for your retirement, so you can enjoy life after work!</p>
<h3>If you are an existing user, then <a href=<%= new_user_session_path %>>log-in</a></h3>
<h3>Otherwise, <a href=<%= new_user_registration_path %>>sign-up</a> and we can get saving</h3>
<h3>Or, <a <%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>.</h3>